helloworld/blueprints/articles.py
from flask import Blueprint
from flask import render_template, request, redirect, abort, url_for

from helloworld import model

blueprint = Blueprint('articles', __name__)

@blueprint.route('/', methods=['GET'])
def index():
    db_session = model.Session()
    articles = db_session.query(model.Article)\
        .order_by(model.Article.posted_at.desc()).all()
    return render_template('articles/index.html', articles=articles)

@blueprint.route('/<int:aid>')
def show(aid):
    db_session = model.Session()
    article = db_session.query(model.Article).get(aid)
    return render_template('articles/show.html', article=article)

@blueprint.route('/new', methods=['POST'])
def create():
    redirect_url = None 
    if 'cancel' in request.form:
        redirect_url = url_for('.index')
    else:
        db_session = model.Session()
        article = model.Article(
            title=request.form['title'], body=request.form['body'])
        try:
            db_session.add(article)
            db_session.commit()
            redirect_url = url_for('.index')
        except:
            db_session.abort()
        finally:
            db_session.close()
    if redirect_url:
        return redirect(redirect_url)
    else:
        abort(500)

@blueprint.route('/new', methods=['GET'])
def edit_new():
    return render_template('articles/new.html')

helloworld/blueprints/articles/__init__.py
from flask import Blueprint
from flask import render_template, request, redirect, abort, url_for

from helloworld import model

blueprint = Blueprint('articles', __name__)

@blueprint.route('/', methods=['GET'])
def index():
    db_session = model.Session()
    articles = db_session.query(model.Article)\
        .order_by(model.Article.posted_at.desc()).all()
    return render_template('articles/index.html', articles=articles)

@blueprint.route('/<int:aid>')
def show(aid):
    db_session = model.Session()
    article = db_session.query(model.Article).get(aid)
    return render_template('articles/show.html', article=article)

@blueprint.route('/new', methods=['POST'])
def create():
    redirect_url = None 
    if 'cancel' in request.form:
        redirect_url = url_for('.index')
    else:
        db_session = model.Session()
        article = model.Article(
            title=request.form['title'], body=request.form['body'])
        try:
            db_session.add(article)
            db_session.commit()
            redirect_url = url_for('.index')
        except:
            db_session.abort()
        finally:
            db_session.close()
    if redirect_url:
        return redirect(redirect_url)
    else:
        abort(500)

@blueprint.route('/new', methods=['GET'])
def edit_new():
    return render_template('articles/new.html')

helloworld/controllers/articles.py
from flask import request
from flask import redirect, url_for
from flask import render_template
from flask import current_app

from helloworld import model

class ArticlesController(object):

    def __init__(self):
        self.app_config = current_app.config

    def list_articles(self):
        db_session = model.Session()
        articles = db_session.query(model.Article)\
            .order_by(model.Article.posted_at.desc()).all()
        return render_template('articles.html', articles=articles)
    
    def show_article(self, aid):
        db_session = model.Session()
        article = db_session.query(model.Article).get(aid)
        return render_template('article.html', article=article)
   
    def save_new_article(self):
        redirect_url = None 
        if 'cancel' in request.form:
            redirect_url = url_for('list_articles')
        else:
            db_session = model.Session()
            article = model.Article(
                title=request.form['title'], body=request.form['body'])
            try:
                db_session.add(article)
                db_session.commit()
                redirect_url = url_for('list_articles')
            except:
                db_session.abort()
            finally:
                db_session.close()
        if redirect_url:
            return redirect(redirect_url)
        else:
            abort(500)
  
    def show_new_article(self):
        return render_template('new-article.html')

helloworld/templates/articles/index.html
{% extends "page.html" %}

{% block head %}
    {{ super() }}
    <title>Articles</title>
{% endblock %}

{% block page_body %}
    <h2>Articles</h2>
   
    <p>Post a <a href="{{url_for('articles.edit_new')}}">new</a> article!</p>

    {% if articles|length == 0 %}
    <p>No articles posted so far!</p>
    {% else %}
    <ul>
        {% for article in articles %}
        <li>
           <span>[{{article.posted_at.date()}}]</span>
           <a href="{{url_for("articles.show", aid=article.id)}}">{{article.title|title}}</a>
        </li>
        {% endfor %}
    </ul>
    {% endif %}
{% endblock %}

helloworld/templates/articles/new.html
{% extends "page.html" %}

{% block head %}
    {{ super() }}
    <title>New article</title>
{% endblock %}

{% block page_body %}
    <h2>Write a new article!</h2>
    <form method="post" enctype="application/x-www-form-urlencoded">
      <div class="form-group">
        <label for="title">Title:</label>
        <input type="text" class="form-control" id="input-title" name="title" placeholder="A brief title"/>
      </div>
      <div class="form-group">
        <label for="body">Content:</label>
        <textarea class="form-control" id="input-body" name="body" placeholder="Blah Blah" rows="5"></textarea>
        <p class="help-block">Be short!</p>
      </div>
      <button type="submit" name="save" class="btn btn-success">Save</button>
      <button type="submit" name="cancel" class="btn btn-default">Cancel</button>
    </form>
{% endblock %}

helloworld/templates/articles/show.html
{% extends "page.html" %}

{% block head %}
    {{ super() }}
    <title>Article</title>
{% endblock %}

{% block page_body %}
    <h2>Article: {{article.title|title}}</h2>
    <p>{{article.body}}</p>

    <p><small>Back to <a href="{{url_for('articles.index')}}">articles</a></small></p>
{% endblock %}